# Site settings
author: Andre S.
title: First Week
header-img: img/home-bg.png
email: halodre24@gmail.com
copyright_name: Andre S.
description: > # this means to ignore newlines until "baseurl:"
  New Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MorpheusVibez

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
